Flight features
LeonteDenismsgDev/Flight-Manager pull request #11
Opened 2024-08-02 14:55 UTC by msgIasmina

Backend flight features

2024-08-05 08:39 UTC, LeonteDenismsgDev requested changes
please dont do pull requests this long again

2024-08-05 08:39 UTC, LeonteDenismsgDev commented on src/main/java/msg/flight/manager/controller/flights/FlightController.java
> +@PreAuthorize("hasAuthority('FLIGHT_MANAGER_ROLE')")
What about crews? They cant see their upcoming flights, or shouldnt company managers also see their flights? I suggest a PreAuthorize for each endpoint

2024-08-05 08:39 UTC, LeonteDenismsgDev commented on src/main/java/msg/flight/manager/controller/flights/TemplateController.java
> +    @GetMapping(value = "/getTemplate")
dece value="/getTemplate" cand mai sus ai fara value?

2024-08-05 08:39 UTC, LeonteDenismsgDev commented on src/main/java/msg/flight/manager/persistence/repositories/FlightRepository.java
> +                Criteria.where("type").is("attribute"),
dece controlam daca tipul e attribute cand suntem in flight repository?

2024-08-05 08:39 UTC, LeonteDenismsgDev commented on src/main/java/msg/flight/manager/services/flights/FlightService.java
> +    public ResponseEntity<String> deleteFlight(String flightId) {
missing @Transactional here

2024-08-05 08:39 UTC, LeonteDenismsgDev commented on src/main/java/msg/flight/manager/services/flights/validation/AttributeValidatorFactory.java
> +
Nu lipsesc celelalte tipuri de obiecte sau e menit sa fie doar text, number, date si array?

2024-08-14 06:24 UTC, msgIasmina commented on src/main/java/msg/flight/manager/persistence/repositories/FlightRepository.java
> +                Criteria.where("type").is("attribute"),
pentru ca vrem sa modificam doar ce e vizibil de utiliator  nu si istoricul din el

2024-08-14 06:26 UTC, msgIasmina commented on src/main/java/msg/flight/manager/services/flights/validation/AttributeValidatorFactory.java
> +
la  number e un al factory si el  se ocupa de  precision  number si  number

2024-08-14 06:27 UTC, msgIasmina commented on src/main/java/msg/flight/manager/services/flights/validation/AttributeValidatorFactory.java
> +
nu  avem validatori  pentru  obiecte deoar penytru atributele din obiecte

2024-08-14 06:27 UTC, LeonteDenismsgDev commented on src/main/java/msg/flight/manager/persistence/repositories/FlightRepository.java
> +                Criteria.where("type").is("attribute"),
ok

2024-08-14 06:27 UTC, LeonteDenismsgDev commented on src/main/java/msg/flight/manager/services/flights/validation/AttributeValidatorFactory.java
> +
ok

2024-08-14 07:40 UTC, LeonteDenismsgDev approved these changes
LGTM

2024-08-14 07:40 UTC, merged