Features for Iasmina
LeonteDenismsgDev/Flight-Manager pull request #4
Opened 2024-07-18 14:27 UTC by LeonteDenismsgDev

2024-07-22 12:14 UTC, msgIasmina commented on src/main/java/msg/flight/manager/services/flights/AttributeService.java
> +
as pune partea de validare in alt fisier...

2024-07-22 12:14 UTC, msgIasmina commented on src/main/java/msg/flight/manager/services/flights/AttributeService.java
> +            if(_value.containsKey("type")&& ((String)_value.get("type")).equals("CUSTOM")){
CUTSOM to "object"

2024-07-22 12:17 UTC, msgIasmina commented on src/main/java/msg/flight/manager/services/CompanyService.java
> +    public int getEmployeesNumber(String name){
in loc  sa faci o metoda in care sa  faci un request cu get alll... ai putea sa salvezi company cu 0- n employesss. si cand faci un insert de user pt company sa faci un trigger pe db sa se modifice  numarul de employeees din company

2024-07-22 12:19 UTC, msgIasmina commented on src/main/java/msg/flight/manager/services/CompanyService.java
> +    UserRepository userRepository;
acum ca exista  tabela de company ar trebui adaugat si o verificare la user cand il salvam  sa verificam  daca compania la care ii face contul exista deja

2024-07-22 12:20 UTC, msgIasmina requested changes
changes  for company  features

2024-07-22 12:25 UTC, LeonteDenismsgDev commented on src/main/java/msg/flight/manager/services/CompanyService.java
> +    UserRepository userRepository;
Corect dar nu tine de feature-ul curent. Asta va fii pe alt task

2024-07-25 09:10 UTC, LeonteDenismsgDev commented on src/main/java/msg/flight/manager/services/flights/AttributeService.java
> +            if(_value.containsKey("type")&& ((String)_value.get("type")).equals("CUSTOM")){
Trebuie sa dam merge master cu ce ai facut tu, deoarece nu va functiona in master de altfel

2024-07-25 09:10 UTC, LeonteDenismsgDev commented on src/main/java/msg/flight/manager/services/CompanyService.java
> +    public int getEmployeesNumber(String name){
Asta ar merge pe task separat

2024-07-30 07:01 UTC, msgIasmina approved these changes

2024-07-30 07:05 UTC, merged